build:
  stage: build
  # instead of calling g++ directly you can also use some build toolkit like make
  # install the necessary build tools when needed
  before_script:
     - apt update && apt -y install build-essential make cmake
  script:
    - mkdir build && cd build && cmake .. && make 
