CANopen: CANopen::Socket Class Reference
CANopen::Socket Class Reference
Canopen object able to send command through a CAN interface using UNIX sockets.
#include <socket.h>
Public Member Functions
Socket (std::string ifname, int verbose_level=0)
Constructor.
Socket (std::string ifname, uint32_t cob_id, int verbose_level=0)
Constructor.
int bind ()
return true if the can interface is successfully bound
void send (const Message &&msg)
Function to send a CAN message.
std::shared_ptr< Message > receive ()
Private Attributes
int m_socket
std::string m_ifname
int m_verbose_level
Detailed Description
Canopen object able to send command through a CAN interface using UNIX sockets.
Constructor & Destructor Documentation
Socket() [1/2]
CANopen::Socket::Socket (std::string ifname, int verbose_level = 0)
Constructor.
Parameters
ifname : Name of the can interface ex:"can0"
verbose : Display the different message sent.
References bind(), m_ifname, m_socket, and m_verbose_level.
Referenced by Socket().
Socket() [2/2]
CANopen::Socket::Socket (std::string ifname, uint32_t cob_id, int verbose_level = 0)
Constructor.
Parameters
ifname : Name of the can interface ex:"can0"
cob_id : Filtering only frame with this ID.
verbose : Display the different message sent.
References m_socket, and Socket().
Member Function Documentation
send()
void CANopen::Socket::send (const Message && msg)
Function to send a CAN message.
Parameters
msg : CAN frame to send
References m_socket.
Member Data Documentation
m_ifname
std::string CANopen::Socket::m_ifname private
CAN interface name
Referenced by bind(), and Socket().
m_socket
int CANopen::Socket::m_socket private
Can socket
Referenced by bind(), send(), and Socket().
m_verbose_level
int CANopen::Socket::m_verbose_level private
Verbose mode
Referenced by Socket().
The documentation for this class was generated from the following files:
/home/adev/Documents/STECH/test_merge/canopen/include/socket.h
/home/adev/Documents/STECH/test_merge/canopen/src/socket.cpp